use serde::{Deserialize, Deserializer, Serialize};

/// Accept both `"thought": "string"` and `"thought": ["a", "b"]`
fn deserialize_thought<'de, D>(deserializer: D) -> Result<Vec<String>, D::Error>
where
    D: Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum StringOrVec {
        Vec(Vec<String>),
        String(String),
    }
    match StringOrVec::deserialize(deserializer)? {
        StringOrVec::Vec(v) => Ok(v),
        StringOrVec::String(s) => Ok(vec![s]),
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentPlan {
    #[serde(default, deserialize_with = "deserialize_thought")]
    pub thought: Vec<String>,
    pub tasks: Vec<AgentTask>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentTask {
    pub task_id: String,
    pub tool_type: String,
    pub description: String,
    #[serde(default)]
    pub depends_on: Vec<String>,
    /// Optional: Reference a previous task_id whose raw output should be
    /// appended to this task's description. Used by `reply_to_request` to
    /// forward large tool outputs verbatim without LLM regeneration.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

pub const REACT_AGENT_PROMPT: &str = r#"--- INTERNAL ACTION & REASONING LOOP ---
You operate in a multi-turn agentic loop. You have tools (Tools) at your disposal.

AVAILABLE TOOLS (TOOLS):
{available_tools}
- TOOL `reply_to_request`: You must use this tool when you have gathered enough information and are ready to provide your final conversational answer to the user. ALL of your character traits, personality, and prompt instructions apply to the `description` field of this tool. This is the ONLY way to answer the user.
  - OUTPUT FORWARDING: If the user asks you to reproduce, echo, or relay a tool's output verbatim, add a `"source": "<task_id>"` field referencing the task whose raw output should be appended to your description. The engine will inject the full, unmodified tool output after your description text.

[RULES OF ENGAGEMENT]
1. TOOL-FIRST FOR FACTS: Use tools to verify factual claims, technical details, and specific real-world entities. For greetings, opinions, and conversation that don't involve verifiable facts, reply directly.
2. THINKING PHASE (CHAIN-OF-THOUGHT): Before you take any action, you are highly encouraged to think out loud. Use the `thought` field to reason through your plan before acting.
3. JSON OUTPUT: Respond with one JSON block per turn. The system loops — you get another turn after tools execute.
4. TIGHT FEEDBACK LOOPS: If a step depends on the output of a previous step, DO NOT try to chain them in a single response array. Execute the first step, end your response, wait for the Observation data on the next turn, and then proceed.
5. PARALLEL EXECUTION: You may chain multiple tools in the `"tasks"` array ONLY if they are completely independent parallel actions (e.g. searching 3 different files at once).
6. CRITICAL LOOP CONSTRAINT: You are trapped in an execution loop. The user will ONLY see the text you place inside the `reply_to_request` tool description. Any conversational text you write outside the JSON block is invisible to the user and is strictly for your own internal reasoning.
7. AVOID REDUNDANT EXECUTION: If the exact same tool call with the exact same parameters already has results in your timeline, use those existing results. Re-execution is valid when: you need fresh or updated data (e.g. re-reading a file after writing to it), you need different parameters (different line range, different query), or the previous attempt failed.
8. PROACTIVE EXECUTION: NEVER narrate what you intend to do. Execute first, confirm after. Bad: "I'll change the theme to professional now." Good: (execute update_theme + render, then reply) "done — switched from cyberpunk to professional." The user hired you because you DO things, not because you describe things you might do.
9. VISUAL QA: You have native vision. After producing ANY artifact (PDF, image, file), you MUST visually inspect it before delivering. For PDFs, review the [VISUAL_QA] preview image. For generated images, look at the result. Never deliver without looking first.
10. PROSE DEFAULT: Write in natural prose unless the user requested structure.


[SYSTEM ISOLATION PROTOCOL]
You may occasionally see messages like `[CRITICAL SYSTEM ERROR]`, `[SYSTEM COMPILER ERROR]`, or `[INTERNAL AUDIT: INVISIBLE TO USER]` injected into your timeline. 
These are **INTERNAL SYSTEM TELEMETRY** messages generated by your own background daemons or the internal safety Observer. 
1. The user CANNOT see these messages. 
2. The user did NOT write these messages, and they are NOT reacting to them.
3. The `[ISOLATED EXECUTION TIMELINE]` tag separates the user's actual chat from your internal reasoning context. The user ONLY sees what is above that tag.
4. **NEVER** apologize to the user for these errors. 
5. **NEVER** acknowledge that an error occurred in your final reply to the user.
6. When you see an internal error or Observer block, silently correct the formatting or capability violation in your next JSON payload, and construct your `reply_to_request` as a natural, seamless continuation of the *original* conversation with the user.

"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_react_prompt_contains_tool_first_rule() {
        assert!(REACT_AGENT_PROMPT.contains("TOOL-FIRST FOR FACTS"),
            "REACT_AGENT_PROMPT must contain tool-first rule");
        assert!(REACT_AGENT_PROMPT.contains("reply_to_request"),
            "REACT_AGENT_PROMPT must reference reply_to_request tool");
    }

    #[test]
    fn test_react_prompt_preserves_tool_first() {
        assert!(REACT_AGENT_PROMPT.contains("TOOL-FIRST"),
            "Rule 1 (TOOL-FIRST) must still be present");
    }

    #[test]
    fn test_react_prompt_preserves_prose_default() {
        assert!(REACT_AGENT_PROMPT.contains("PROSE DEFAULT"),
            "Rule 10 (PROSE DEFAULT) must still be present");
    }


    #[test]
    fn test_plan_deserialization() {
        let json = r#"{"thought": "test", "tasks": [{"task_id": "r1", "tool_type": "reply_to_request", "description": "hello"}]}"#;
        let plan: AgentPlan = serde_json::from_str(json).unwrap();
        assert_eq!(plan.tasks.len(), 1);
        assert_eq!(plan.tasks[0].tool_type, "reply_to_request");
    }

    #[test]
    fn test_plan_deserialization_with_source() {
        let json = r#"{"thought": ["step1", "step2"], "tasks": [{"task_id": "r1", "tool_type": "reply_to_request", "description": "here:", "source": "read_1"}]}"#;
        let plan: AgentPlan = serde_json::from_str(json).unwrap();
        assert_eq!(plan.tasks[0].source.as_deref(), Some("read_1"));
    }
}
