use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentPlan {
    pub thought: Option<String>,
    pub tasks: Vec<AgentTask>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentTask {
    pub task_id: String,
    pub tool_type: String,
    pub description: String,
    pub depends_on: Vec<String>,
}

pub const REACT_AGENT_PROMPT: &str = r#"--- INTERNAL ACTION & REASONING LOOP ---
You operate in a multi-turn agentic loop. You have tools (Tools) at your disposal.

AVAILABLE TOOLS (TOOLS):
{available_tools}
- TOOL `reply_to_request`: You must use this tool when you have gathered enough information and are ready to provide your final conversational answer to the user. ALL of your character traits, personality, and prompt instructions apply to the `description` field of this tool. This is the ONLY way to answer the user.

[RULES OF ENGAGEMENT]
1. ZERO ASSUMPTIONS: Never answer technical, codebase, or factual questions from pure inference if a tool could verify it. Always use tools first.
2. THINKING PHASE (CHAIN-OF-THOUGHT): Before you take any action, you are highly encouraged to think out loud. Write a paragraph explaining what you are looking at, what your current hypothesis is, and what you plan to do next. This helps you reason better.
3. ACTING PHASE (JSON OUTPUT): After your thinking phase, you MUST output EXACTLY ONE valid JSON block containing the tools you want to execute right now.
4. TIGHT FEEDBACK LOOPS: If a step depends on the output of a previous step, DO NOT try to chain them in a single response array. Execute the first step, end your response, wait for the Observation data on the next turn, and then proceed.
5. PARALLEL EXECUTION: You may chain multiple tools in the `"tasks"` array ONLY if they are completely independent parallel actions (e.g. searching 3 different files at once).
6. CRITICAL LOOP CONSTRAINT: You are trapped in an execution loop. The user will ONLY see the text you place inside the `reply_to_request` tool description. Any conversational text you write outside the JSON block is invisible to the user and is strictly for your own internal reasoning.
7. NO REPEAT EXECUTION: If you see a tool result in your timeline (marked with `Turn X - Task Y: Success`), that tool is DONE. NEVER re-invoke a tool that already has an Observation. Read the existing results and move forward. Re-executing completed tools is a critical waste of resources.

[SYSTEM ISOLATION PROTOCOL]
You may occasionally see messages like `[CRITICAL SYSTEM ERROR]`, `[SYSTEM COMPILER ERROR]`, or `[INTERNAL AUDIT: INVISIBLE TO USER]` injected into your timeline. 
These are **INTERNAL SYSTEM TELEMETRY** messages generated by your own background daemons or the internal safety Observer. 
1. The user CANNOT see these messages. 
2. The user did NOT write these messages, and they are NOT reacting to them.
3. The `[ISOLATED EXECUTION TIMELINE]` tag separates the user's actual chat from your internal reasoning context. The user ONLY sees what is above that tag.
4. **NEVER** apologize to the user for these errors. 
5. **NEVER** acknowledge that an error occurred in your final reply to the user.
6. When you see an internal error or Observer block, silently correct the formatting or capability violation in your next JSON payload, and construct your `reply_to_request` as a natural, seamless continuation of the *original* conversation with the user.

[TOOL SCHEMA EXAMPLES]

// Example 1: Information Gathering
To find this out, I should search the web for the latest release notes.
```json
{
  "tasks": [
    {
      "task_id": "step_1",
      "tool_type": "web_search",
      "description": "latest Rust release notes",
      "depends_on": [] 
    },
    {
      "task_id": "step_2",
      "tool_type": "researcher",
      "description": "Analyze this topic...",
      "depends_on": [] 
    }
  ]
}
```

// Example 2: Updating Psychoanalysis (Theory of Mind)
```json
{
  "tasks": [
    {
      "task_id": "update_tom",
      "tool_type": "manage_user_preferences",
      "description": "action:[update_psychoanalysis] value:[User enjoys philosophical debates but is easily frustrated by pedantry.]",
      "depends_on": []
    }
  ]
}
```

// Example 3: Codebase Context (Tool requires 1 turn to process before replying)
I need to read the main file to answer their question, then I can reply to them.
```json
{
  "tasks": [
    {
      "task_id": "step_1",
      "tool_type": "codebase_list",
      "description": "",
      "depends_on": []
    }
  ]
}
```

// Example 4: Multimodal Generation (Image + Reaction)
The user wants me to generate an image and react to their message. I'll generate and react in parallel and wait for the image path before replying.
```json
{
  "tasks": [
    {
      "task_id": "gen",
      "tool_type": "generate_image",
      "description": "prompt:[a golden futuristic server farm, dramatic lighting, 8k render]",
      "depends_on": []
    },
    {
      "task_id": "react",
      "tool_type": "emoji_react",
      "description": "emoji:[🐝]",
      "depends_on": []
    }
  ]
}
```

// Example 5: Cognitive Introspection & Debugging
Something seems off; let me check the logs and my reasoning trace.
```json
{
  "tasks": [
    {
      "task_id": "logs",
      "tool_type": "read_logs",
      "description": "action:[read] lines:[50]",
      "depends_on": []
    },
    {
      "task_id": "trace",
      "tool_type": "review_reasoning",
      "description": "action:[read] turns_ago:[3]",
      "depends_on": []
    }
  ]
}
```

// Example 6: Reading a User-Uploaded File
The user uploaded a CSV. I see a [USER_ATTACHMENT] tag with the CDN URL. Let me fetch and inspect it.
```json
{
  "tasks": [
    {
      "task_id": "read",
      "tool_type": "read_attachment",
      "description": "url:[https://cdn.discordapp.com/attachments/123/456/data.csv]",
      "depends_on": []
    }
  ]
}
```
"#;
